### ISSUE TITLE
Backup Solutions

### ISSUE THREAD

**Issue by Zach-ATK** [Ops-201-Team-Name/Ops-201-Team-Name#12]

**Comment by Zach-ATK** [comment]
Zach's notes:
Linux -
installing freefilesync is different, it needs to be unzipped in a specific way, and saying "customize as needed, isn't good for a non-tech person, nor SOP. The IT person setting things up needs clarity. For instance, what folders should be backed up?

- It would make sense to show how to add freefilesync onto the 'favorites' tab if needed
- Google workspace (If we are wanting an auto backup to google drive, there is software needed. Google Drive for Desktop is for windows, IDK what is the standard for linux)

- It may be that having a separate SOP for IT and for users would be good. One would show start to finish setting up a new computer for use (IT) the other would show how to operate the systems as the user.

**Comment by HeraldoM332** [comment]
I have put possible solutions in my SOP and have taken the criticism from my teammates to improve upon my SOP

**Comment by HeraldoM332** [comment]
I have finished with all the required issues and have only a comment regarding google drive and how it is not able to be downloaded for Linux but aside from that everything seems good and easy to follow. I have not implemented both IT users and new Users separately, however it should be able to be managed by both
