### ISSUE TITLE
User Provisioning

### ISSUE THREAD

**Issue by Zach-ATK** [Ops-201-Team-Name/Ops-201-Team-Name#23]
- [x] Setup a single endpoint as you would for a new user:
     - [x] This should include connecting the new user to whatever network or cloud resources they will use (shared folders, backup systems, email address connected to email client, etc.).
- [x] Use any available tooling to minimize MSP labor in this process.
     - [ ] Stretch Goal: partially or fully automate this process (imagine entering only the new user's name and email into a script and then letting the setup take care of itself).

**Comment by Zach-ATK** [comment]
Sounds like we need to create a template VM

**Comment by Random9904** [comment]
This issue is solved by [Onboarding](https://github.com/Ops-201-Team-Name/Ops-201-Team-Name/wiki/Onboarding)

**Comment by HeraldoM332** [comment]
SOP has been reviewed and is detailed and answers questions precisely
