### ISSUE TITLE
Software List

### ISSUE THREAD

**Issue by Zach-ATK** [Ops-201-Team-Name/Ops-201-Team-Name#28]
Please put whatever software is required for your section here:

- Thunderbird (email)

**Comment by HeraldoM332** [comment]
FreefileSync
Google Workspace

**Comment by Zach-ATK** [comment]
Completed:
FreefileSync
Thunderbird
Google Drive for Desktop

**Comment by HeraldoM332** [comment]
Google Drive for Desktop
