### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by Zach-ATK** [Ops-201-Team-Name/Ops-201-Team-Name#9]
- [x] You will need to establish technology and protocols for secure remote access.
- [x] You (the MSP) will need remote Admin/root access for management and troubleshooting.
- [x] Depending on the scenario, users may also need remote access on occasion. Evaluate the client's needs and implement an appropriate solution.
- [ ] Stretch Goal: implement a solution for remotely accessing a user's system over the internet to help them troubleshoot a problem. Assume that the MSP must securely access the machine over the internet.

**Comment by HeraldoM332** [comment]
SOP has been reviewed and is detailed and answers questions precisely
